### ISSUE TITLE
Make the self tests work for python3

### ISSUE THREAD

**Issue by jenskje** [texttest/capturemock#2]
Currently all cmdline version tests fail, due to server.py et. al. not being ported to python3. Unfortunately it isn't as easy as running 2to3 on the code. The imports for config and replayinfo need special treatment. We'll try to fix this from the Jeppesen side, but would probably be good with some input from @gjb1002.

**Comment by jenskje** [comment]
We're now in a state were all but one test run on python3. We'll leave that to @gjb1002 :slightly_smiling_face:. Thanks to @johangill for helping out to get to this state.

**Comment by gjb1002** [comment]
The cmdline tests still don't work at all on Windows, which means I can't currently investigate the failing test. Will try to take a look at home sometime but don't know when that will be. On Windows the .exe file mechanism needs redoing, probably using cx_freeze instead of py2exe. Will probably be next month before I get to that though.

**Comment by jenskje** [comment]
I think we are in a good enough state to be able to make changes with some confidence. The failing test is somewhat of a special case from what I understand. I don't think this is an issue that stops us from going forward.

**Comment by gjb1002** [comment]
Have now sprouted a separate issue #3 for the Windows problems.

**Comment by gjb1002** [comment]
I've now got all but 2 tests running green on Windows. These are under "xmlrpc" and I don't believe this feature is used by anyone (certainly not the TextTest self-tests which are the main driver here).

The test that didn't work for @jenskje worked fine for me. I suspect it was something to do with having a  mixed environment of Python 2 and Python 3 processes.

**Comment by gjb1002** [comment]
xmlrpc tests seem to have been working for a while. I guess we forgot to close this.
