### ISSUE TITLE
Version 2.0.5 is not python2 compatible

### ISSUE THREAD

**Issue by johangill** [texttest/capturemock#6]
There are several changes in the latest release (2.0.5) that are not python2 compatible.
This is  the version one get with `pip install` on python2.

Some examples:
    
- __init__.py:246: newline keyword argument
    `with open(fn1, newline=None) as fp1, open(fn2, newline=None) as fp2:`
- clientservertraffic.py: 5
  server.py:21
   `from urllib.request import urlopen`

**Comment by gjb1002** [comment]
Unfortunately I don't think I have the resources to support Capturemock on Python 2 into the future. I could perhaps have been clearer about this with the Capturemock 2.* series and made a more definite decision to drop it, but the basic issue is that I don't have any such environments myself any more and that the code is quite sensitive to different versions.

Python 2 reached its end of life going on for 2 years ago now. If you still need support in Capturemock, I can only suggest you fork an old version - probably a 1.x version - and go with that.

**Comment by johangill** [comment]
I am fine with it not beeing supported on python2.

But I think the documentation should be updated to state that. And it should probably no longer be released to pip on python2.

I would apreciate if a tag could be created on release 2.0 which still works on python2.
It would make it easier to checkout an older release.

Thanks

**Comment by gjb1002** [comment]
Have tagged release 2.0 now, will try to remedy the rest with the next release.

**Comment by johangill** [comment]
Thanks
